[workspace]
resolver = "2"
members = ["bertalign-rs", "bertalign-examples"]

[workspace.package]
version = "0.2.0"
edition = "2021"

[workspace.dependencies]
bertalign-rs = { path = "./bertalign-rs" }
