[package]
name = "bertalign-examples"
version.workspace = true
edition.workspace = true

[dependencies]
bertalign-rs = { workspace = true }
candle-core = { version = "0.9.1" }

[features]
metal = ["bertalign-rs/metal"]
cuda = ["bertalign-rs/cuda"]
mkl = ["bertalign-rs/mkl"]
